#pragma once

#ifndef __ENGINE_ENUM_H__

BEGIN(ENGINE)

enum DISPLAY_MODE {	MODE_FULL, MODE_WIN };

enum TEXTURE_TYPE {	TEXTURE_NORMAL,	TEXTURE_CUBE };

enum SCENE_TYPE { SCENE_MAIN, SCENE_SUB, SCENE_END };

enum SCENE_KIND { SCENE_LOGO, SCENE_STAGE };

enum BUFFER_TYPE {
	BUFFER_RCCOL, BUFFER_RCTEX, BUFFER_TERRAINCOL,
	BUFFER_TERRAINTEX, BUFFER_CUBETEX, BUFFER_RCTEXLYING, BUFFER_CUBECOL, BUFFER_END
};

enum RESOURCE_TYPE { RESOURCE_STATIC, RESOURCE_DYNAMIC, RESOURCE_END };

enum LAYER_TYPE { LAYER_ENVIRONMENT, LAYER_OBJECT, LAYER_EFFECT, LAYER_UI, LAYER_END };

enum ANGLE_TYPE { ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END };

enum PIVOT_TYPE { PIVOT_BOTTOM, PIVOT_MIDDLE, PIVOT_TOP, PIVOT_LEFT, PIVOT_RIGHT, PIVOT_FRONT };

enum BUILDING_UI_TYPE { BUILDING_TILE, BUILDING_RIDES, BUILDING_COMFY, BUILDING_DESIGN };

enum TILE_TYPE { TILE_NONE, TILE_TILE, TILE_RIDES };

enum RIDE_TYPE {RIDE_VIKING, RIDE_SPINHORSE, RIDE_FERRIS, RIDE_GYRODROP, RIDE_ROLLERCOASTER, RIDE_SPINTEACUP, RIDE_GYROSWING, RIDE_END};

END

#define __ENGINE_ENUM_H__
#endif